/* ======================= glossary ======================= */
(function(){
var d = App.gloss;
/* --- instructions and front end --- */
d('isa','ISA','Instruction set architecture: the contract between software and hardware (x86-64 here). It fixes what each instruction does to registers and memory, not how the silicon does it.');
d('uop','µop (micro-op)','A simple internal operation the core actually schedules and executes. One x86 instruction becomes one or more µops.');
d('mop','macro-op','AMD\'s tracking unit between x86 instructions and µops. On Zen a macro-op can carry a load, an ALU operation and a store together; the retire queue tracks macro-ops.');
d('pc','PC / RIP','Program counter: the virtual address of the next instruction to fetch. Called RIP on x86-64.');
d('bp','branch predictor','Hardware that guesses, before decode, whether a branch is taken and where it goes, so fetch never waits for the branch to execute.');
d('btb','BTB','Branch target buffer: a cache keyed by fetch address that remembers where previously seen branches jumped. A BTB hit lets fetch redirect in the same cycle.');
d('ras','RAS','Return address stack: a small hardware stack that pushes on CALL and pops on RET to predict return targets.');
d('l1i','L1i','Level-1 instruction cache. 64 KB, 4-way on your Zen+ core. Fetch reads 32 bytes per cycle from it.');
d('itlb','iTLB','Instruction TLB: translates the fetch address (virtual) to a physical address for the L1i tag check.');
d('fetchwin','fetch window','The aligned block of bytes fetch reads in one cycle (32 bytes on Zen+). Instructions are carved out of it afterwards.');
d('predecode','predecode / pick','Finds where each variable-length x86 instruction starts and ends inside the fetch window, so decoders get whole instructions.');
d('decode','decode','Translates x86 instructions into macro-ops / µops. Zen+ decodes up to 4 x86 instructions per cycle.');
d('opcache','op cache','A cache of already-decoded µops, keyed by instruction address. A hit skips predecode and decode entirely. 2K entries on Zen/Zen+.');
d('uq','µop queue','A buffer between decode and rename that absorbs rate mismatches between the front end and the back end.');
d('fusion','macro-fusion','Merging a compare/test with the following conditional jump into one operation. On Zen it happens at dispatch; this model shows it fused from decode on for readability.');
d('zx','zero extension','Filling the upper bits of a wider destination with zeros. movzbl reads 1 byte and writes 32 bits; writing a 32-bit register also zeroes bits 63:32.');
d('modrm','ModRM / SIB','Encoding bytes that say which registers and addressing form an instruction uses. SIB adds scale, index and base for addresses like (%rdx,%rax,8).');
d('rex','REX prefix','A prefix byte (0x40-0x4F) that enables 64-bit operand size (REX.W) and access to r8-r15.');
/* --- rename / OoO --- */
d('rename','register renaming','Mapping each architectural register write to a fresh physical register, so only true data dependencies (RAW) remain.');
d('rat','RAT','Register alias table: for every architectural register, the physical register currently holding its newest value. Read for sources, written for destinations at rename.');
d('crat','committed RAT','The architectural-state copy of the RAT, updated only at retirement. After a squash the speculative RAT is rebuilt from it.');
d('prf','PRF','Physical register file: the actual storage for register values. Zen+ has 168 integer entries; each has a ready bit.');
d('freelist','free list','The list of physical registers holding nothing live. Rename takes from it; retirement (and squash) give registers back.');
d('dispatch','dispatch / allocate','Placing renamed operations into the back end: one retire-queue entry, scheduler entries, and load/store-queue entries. Stalls if any of those is full.');
d('rob','ROB / retire queue','Reorder buffer: an in-order circular buffer of every in-flight instruction. Instructions enter in program order, may finish out of order, and leave (retire) only from the head, in order. 192 entries on Zen+ (96 per SMT thread).');
d('sched','scheduler','A queue of waiting µops that watches for their source operands to become ready and picks ready ones for execution. Zen+ has four 14-entry ALU schedulers and two 14-entry AGU schedulers.');
d('wakeup','wakeup','When a µop\'s result is about to be produced, its destination tag is broadcast to the schedulers; waiting µops that need that tag mark the operand ready.');
d('issue','issue / select','Each cycle, each execution port takes the oldest ready µop from its scheduler.');
d('port','execution port','An entry point into a functional unit. Zen+ integer side: 4 ALU ports and 2 AGU ports.');
d('alu','ALU','Arithmetic-logic unit: adds, compares, logic, shifts, branch resolution.');
d('agu','AGU','Address generation unit: computes base + index*scale + displacement for loads and stores.');
d('bypass','bypass network','Wires that forward a result straight from a unit\'s output to the next µop\'s input, without a round trip through the register file.');
d('lsu','load/store unit','The part of the core that holds in-flight loads and stores, translates their addresses and accesses the L1d.');
d('lq','load queue','Holds every in-flight load in program order until it retires. 44 entries on Zen+.');
d('sq','store queue / store buffer','Holds every in-flight store (address + data) in program order. Before retirement it enables forwarding; after retirement its entries are committed to the L1d one at a time. 44 entries on Zen+.');
d('sta','store-address µop','The half of a store that computes the address (on an AGU) and writes it into the store-queue entry.');
d('std','store-data µop','The half of a store that delivers the value to be stored into the store-queue entry.');
d('stlf','store-to-load forwarding','A load whose address matches an older, not-yet-committed store takes its value from the store queue instead of the cache.');
d('disamb','memory disambiguation','Deciding whether a load may run before older stores whose addresses are still unknown. Hardware predicts \'no overlap\' and replays the load if that turns out wrong.');
d('retire','retire','The in-order step where a finished instruction\'s results become architectural state: its old physical registers are freed and its store becomes eligible to commit.');
d('commit','store commit','Writing a retired store from the store queue into the L1d. Only here does the store become visible to other cores.');
d('senior','senior store','A store that has retired but still sits in the store queue waiting to commit. It must still forward to younger loads.');
d('squash','squash / flush','Discarding every instruction younger than a mispredicted branch (or a faulting instruction): their ROB, scheduler, queue entries and physical registers are released.');
d('mispredict','misprediction','The branch predictor guessed wrong. Detected when the branch executes; costs the refill time of the front end \u2014 tens of cycles, and directly measurable with a branch-heavy loop over sorted vs. random data.');
d('spec','speculative execution','Executing instructions before it is known that they are on the correct path. Their effects stay inside the core until retirement.');
d('smt','SMT','Simultaneous multithreading: two hardware threads share one core\'s pipeline and caches. Your 3750H has 4 cores, 8 threads.');
d('ipc','IPC','Instructions retired per cycle.');
d('mab','MAB / MSHR','Miss address buffer (AMD) / miss status holding register: one entry per outstanding cache-line miss. Later misses to the same line merge into the existing entry.');
/* --- cache vocabulary --- */
d('line','cache line','The 64-byte unit every cache level stores and transfers.');
d('set','set','The group of lines an address\'s index bits select. An address can live only in its own set.');
d('way','way','One slot within a set. An 8-way cache has 8 places per set for any given index.');
d('tag','tag','The upper address bits stored with a line so a lookup can confirm which memory block occupies that slot.');
d('index','index','The address bits that select a set.');
d('offset','offset','The low 6 address bits that select a byte within a 64-byte line.');
d('hit','hit','The requested line is present in that cache level.');
d('miss','miss','The requested line is not present; the request goes to the next level.');
d('valid','valid bit','Marks whether a way holds a real line. A tag match counts only if valid = 1.');
d('dirty','dirty bit','Marks that a line was written after it was filled, so the next level holds a stale copy.');
d('wbk','write-back','A write updates only the cache line and sets its dirty bit; the next level is updated only when the line is evicted.');
d('wthru','write-through','Every write is also sent to the next level immediately.');
d('walloc','write-allocate','On a write miss, the line is first fetched into the cache, then written.');
d('rfo','RFO','Read for ownership: fetching a line with exclusive permission because the core intends to write it. Other cached copies are invalidated.');
d('evict','eviction','Removing a line from a full set to make room. A dirty victim must be written back first.');
d('plru','pseudo-LRU','A cheap approximation of least-recently-used replacement: a small binary tree of bits per set that points toward the older half at each level.');
d('vipt','VIPT','Virtually indexed, physically tagged: the L1 set is chosen with virtual-address bits while the TLB translates in parallel; the tag compare uses the physical address. Works because bits 11:6 are inside the 4 KB page offset and never change in translation.');
d('incl','inclusive cache','A cache that holds a copy of every line held by the smaller caches above it. Zen+\'s L2 is inclusive of its L1s.');
d('victimc','victim cache','A cache filled only with lines evicted from the level above. Zen+\'s L3 is filled from L2 victims and is mostly exclusive of the L2s.');
d('shadow','shadow tags','Copies of every L2\'s tags kept inside the L3. They let the L3 know which core might hold a line without asking all of them.');
d('pfilter','probe filter','A structure that records which caches may hold a line, so coherence probes go only where needed instead of to every cache.');
d('ccx','CCX','Core complex: a group of up to four Zen cores sharing one L3. Your 3750H has one CCX with 4 MB of L3.');
d('mlp','memory-level parallelism','Having several cache misses outstanding at once so their latencies overlap. Zen/Zen+ allow 50 outstanding L2-to-L3 misses per core and 96 L3-to-memory misses.');
d('ltu','load-to-use latency','Cycles from a load issuing to the first cycle a dependent instruction can use its value.');
d('wset','working set','The set of addresses a program actively uses during some interval.');
d('sloc','spatial locality','The tendency to access addresses near recently accessed ones.');
d('tloc','temporal locality','The tendency to access the same address again soon.');
d('sram','SRAM','Static RAM: 6 transistors per bit, fast, no refresh. Caches and register files are SRAM.');
d('dramcell','DRAM cell','One transistor plus one capacitor per bit (1T1C). Dense and cheap, but reading drains the capacitor and charge leaks, so rows need restoring and periodic refresh.');
/* --- translation --- */
d('va','virtual address','The address a program uses. 48 bits wide on x86-64 with 4-level paging.');
d('pa','physical address','The address actually sent to caches and DRAM after translation.');
d('page','page','The unit of translation: 4 KB by default, also 2 MB and 1 GB huge pages.');
d('vpn','VPN','Virtual page number: the virtual address with its page-offset bits removed.');
d('pfn','PFN','Page frame number: the physical page number a VPN maps to.');
d('mmu','MMU','Memory management unit: the TLBs, page walkers and permission checks that turn virtual addresses into physical ones.');
d('tlb','TLB','Translation lookaside buffer: a cache of recent VPN-to-PFN translations plus permission bits.');
d('dtlb','DTLB','Data TLB. Zen+: 64-entry fully associative L1 DTLB (all page sizes) backed by a 1536-entry L2 TLB (no 1 GB pages).');
d('pte','PTE','Page-table entry: 8 bytes holding a physical frame number plus flag bits (present, writable, user, accessed, dirty, no-execute...).');
d('pml4','PML4 / PDPT / PD / PT','The four page-table levels on x86-64. Each is one 4 KB page of 512 eight-byte entries, indexed by 9 bits of the virtual address.');
d('cr3','CR3','The control register holding the physical address of the current process\'s top-level page table (and its PCID). Writing it switches address spaces.');
d('walk','page walk','Reading the page-table entries level by level to translate an address after a TLB miss. Each step is a real memory load that goes through the data caches.');
d('pwc','page-walk cache','Caches upper-level page-table entries so a walk can skip levels. 7-cpu.com reports a 64-entry cache for PML4E/PDPE entries on Zen.');
d('reach','TLB reach','How much memory the TLB can map at once: entries × page size. 64 × 4 KB = 256 KB for the L1 DTLB.');
d('huge','huge page','A 2 MB (or 1 GB) page. One TLB entry covers 512× (or 262144×) more memory, and the walk ends one (or two) levels early.');
d('pcid','PCID','Process-context identifier: a 12-bit tag on TLB entries so switching CR3 need not flush every translation.');
d('pf','page fault','Exception 14 (#PF), raised when a translation is missing or a permission check fails. CR2 receives the faulting address and the kernel handles it.');
d('ftouch','first-touch','Linux\'s default NUMA policy: a page is physically allocated on the node of the CPU that first writes it, not the one that called malloc.');
/* --- fabric, DRAM, I/O --- */
d('fabric','Infinity Fabric (data fabric)','AMD\'s on-chip interconnect linking the CCX, memory controllers, graphics and I/O. Coherent: it routes requests and coherence probes.');
d('umc','UMC','Unified memory controller: queues memory requests, schedules DRAM commands, enforces timing rules, and performs refresh.');
d('channel','memory channel','An independent 64-bit data bus plus command/address bus to a set of DIMMs. Your laptop has two.');
d('dimm','DIMM / rank','A memory module. A rank is the set of chips that together drive the 64-bit bus (8 chips × 8 bits).');
d('bank','bank / bank group','An independent cell array inside each DRAM chip. DDR4 x8 chips have 16 banks in 4 bank groups; different banks can work in parallel.');
d('row','row / column','A bank is a matrix of rows × columns. A whole row is opened at once; reads then select columns from it.');
d('rowbuf','row buffer','The bank\'s sense amplifiers after ACT: they hold the open row. Reads from the open row are fast; any other row needs PRE + ACT first.');
d('act','ACT / RD / WR / PRE / REF','DRAM commands: activate (open a row into the row buffer), read, write, precharge (close the row), refresh.');
d('tcl','CL, tRCD, tRP, tRAS','DRAM timings: CL = RD to first data; tRCD = ACT to RD; tRP = PRE to next ACT; tRAS = ACT to PRE minimum.');
d('burst','burst','One DDR4 read transfers 8 beats on the 64-bit bus: 8 × 8 bytes = 64 bytes, exactly one cache line.');
d('refresh','refresh','Rewriting every row before its capacitors leak. DDR4 issues REF about every 7.8 µs and covers every row within 64 ms.');
d('pcie','PCIe','The serial point-to-point link to devices such as the NVMe SSD. Traffic travels as packets called TLPs.');
d('tlp','TLP','Transaction-layer packet on PCIe: memory read (non-posted, answered by a completion with data), memory write (posted, no reply), message, etc.');
d('rc','root complex','The CPU-side end of PCIe that turns core and fabric requests into TLPs and device TLPs into memory requests.');
d('mmio','MMIO','Memory-mapped I/O: device registers appear at physical addresses; ordinary loads and stores to them reach the device instead of DRAM.');
d('bar','BAR','Base address register: tells the system where a PCIe device\'s MMIO registers sit in the physical address space.');
d('doorbell','doorbell','An MMIO register the driver writes to tell a device that new work is in a queue.');
d('dma','DMA','Direct memory access: a device reads or writes host memory itself, without the CPU copying each byte.');
d('iommu','IOMMU','An MMU for devices: translates device-visible addresses (IOVAs) to physical addresses and blocks access outside what the OS mapped.');
d('iova','IOVA','I/O virtual address: the address a device uses for DMA when an IOMMU is enabled.');
d('msix','MSI-X','Message-signaled interrupts: a device raises an interrupt by writing a small message to a special address the interrupt controller watches.');
d('nvme','NVMe','The SSD protocol built around memory-resident submission and completion queues plus doorbell registers. io_uring was designed around the same ring idea.');
d('iocoh','I/O coherence','On x86, DMA traffic is snooped against CPU caches: device reads see dirty cached data and device writes invalidate stale cached copies.');
/* --- memory types, stores, ordering --- */
d('memtype','memory type','How the caches treat an address range: WB (write-back, normal RAM), WT (write-through), WC (write-combining), UC (uncacheable), WP (write-protect). Set by PAT bits in page tables and by MTRRs.');
d('pat','PAT / MTRR','Page attribute table (per-page memory type via PTE bits) and memory type range registers (per physical range). Together they decide the memory type.');
d('wc','write-combining','Stores to WC memory are gathered in a WC buffer and sent out as one full-line write, without reading the line first and without caching it.');
d('nt','non-temporal store','A store hint (movnti, movntdq) that uses write-combining even on WB memory, avoiding the RFO and not polluting the caches.');
d('clflush','clflush / clwb','Instructions that write a line back to memory (clwb keeps it cached; clflush/clflushopt also evict it).');
d('fence','sfence / lfence / mfence','Ordering instructions. mfence waits for the store buffer to drain before later loads run \u2014 tens of cycles, easy to measure with a tight loop of mfence alone.');
d('tso','x86-TSO','x86\'s memory model: every ordering is preserved except a store followed by a load to a different address, which the store buffer can reorder.');
/* --- coherence --- */
d('coh','cache coherence','The guarantee that all cores observe a single order of writes to each address, even though each core has private caches.');
d('moesi','MOESI','AMD\'s coherence states: Modified, Owned, Exclusive, Shared, Invalid.');
d('st_m','M (Modified)','Only this cache has the line and it is dirty. It may be read and written without asking anyone.');
d('st_o','O (Owned)','This cache has a dirty copy and other caches share it. The owner answers requests with data; memory is stale.');
d('st_e','E (Exclusive)','Only this cache has the line and it is clean. A write upgrades it to M silently.');
d('st_s','S (Shared)','Several caches may hold this clean (or owner-backed) copy. A write first needs the others invalidated.');
d('st_i','I (Invalid)','The line is not usable in this cache.');
d('probe','probe / snoop','A coherence message asking another cache to return, downgrade, or invalidate its copy of a line.');
d('fshare','false sharing','Two cores writing different variables that share one 64-byte line. Each write invalidates the other core\'s copy, so the line bounces between them.');
/* --- prefetch --- */
d('pref','hardware prefetcher','Logic that watches the stream of miss/access addresses and fetches lines it predicts will be needed, before the program asks.');
d('stream','stream prefetcher','Detects accesses to consecutive lines in one direction and runs ahead along them.');
d('stride','stride prefetcher','Detects a constant distance between successive accesses from the same instruction and fetches ahead by that stride.');
d('swpf','software prefetch','Instructions (prefetcht0/t1/t2/nta) that ask the hardware to start fetching a line without waiting for the data.');
d('late','late prefetch','A prefetch that was issued but whose data had not arrived when the demand access came; the access still waits, but less.');
d('pollute','cache pollution','Useless prefetched lines evicting useful ones.');
d('memwall','memory wall','The widening gap between CPU speed and DRAM latency. The reason the whole hierarchy exists.');
})();
