/* ======================= glossary ======================= */
(function(){
var d = App.gloss;
/* --- instructions and front end --- */
d('isa','ISA','Instruction set architecture: the contract between software and hardware (x86-64 here). It fixes what each instruction does to registers and memory, not how the silicon does it.');
d('uop','µop (micro-op)','A simple internal operation the core actually schedules and executes. One x86 instruction becomes one or more µops.');
d('mop','macro-op',"An implementation’s internal grouping of operations. Grouping, fusion and retirement accounting vary. The x86 histogram model tracks instruction records separately from its µops.");
d('pc','PC / RIP','Program counter: the virtual address of the next instruction to fetch. Called RIP on x86-64.');
d('bp','branch predictor','Hardware that guesses, before decode, whether a branch is taken and where it goes, so fetch never waits for the branch to execute.');
d('btb','BTB','Branch target buffer: a cache keyed by fetch address that remembers where previously seen branches jumped. A BTB hit lets fetch redirect in the same cycle.');
d('ras','RAS','Return address stack: a small hardware stack that pushes on CALL and pops on RET to predict return targets.');
d('l1i','L1i',"Level-1 instruction cache. Stores instruction bytes near the frontend. Capacity, associativity and fetch width are implementation-specific.");
d('itlb','iTLB','Instruction TLB: translates the fetch address (virtual) to a physical address for the L1i tag check.');
d('fetchwin','fetch window',"The byte window considered by instruction fetch. The x86 example chooses a 32-byte window; other frontends and ISAs differ.");
d('predecode','predecode / pick','Finds where each variable-length x86 instruction starts and ends inside the fetch window, so decoders get whole instructions.');
d('decode','decode',"Translates architectural instructions into an implementation’s internal operations. The teaching pipeline chooses four instruction groups per cycle.");
d('opcache','op cache',"A structure retaining decoded operations to reduce repeated decode work. Entries, grouping and admission rules depend on the implementation.");
d('uq','µop queue','A buffer between decode and rename that absorbs rate mismatches between the front end and the back end.');
d('fusion','macro-fusion',"Combining adjacent instructions or internal operations. Eligible pairs, stage and accounting differ. This model fuses compare and branch for readability.");
d('zx','zero extension','Filling the upper bits of a wider destination with zeros. movzbl reads 1 byte and writes 32 bits; writing a 32-bit register also zeroes bits 63:32.');
d('modrm','ModRM / SIB','Encoding bytes that say which registers and addressing form an instruction uses. SIB adds scale, index and base for addresses like (%rdx,%rax,8).');
d('rex','REX prefix','A prefix byte (0x40-0x4F) that enables 64-bit operand size (REX.W) and access to r8-r15.');
/* --- rename / OoO --- */
d('rename','register renaming','Mapping each architectural register write to a fresh physical register, so only true data dependencies (RAW) remain.');
d('rat','RAT','Register alias table: for every architectural register, the physical register currently holding its newest value. Read for sources, written for destinations at rename.');
d('crat','committed RAT','The architectural-state copy of the RAT, updated only at retirement. After a squash the speculative RAT is rebuilt from it.');
d('prf','PRF',"Physical register file: storage for renamed register values. The model chooses 48 entries; this is not a vendor capacity.");
d('freelist','free list','The list of physical registers holding nothing live. Rename takes from it; retirement (and squash) give registers back.');
d('dispatch','dispatch / allocate','Placing renamed operations into the back end: one retire-queue entry, scheduler entries, and load/store-queue entries. Stalls if any of those is full.');
d('rob','ROB / retire queue',"Reorder buffer: tracks in-flight work in program order so retirement can remain precise while execution occurs out of order. Record granularity varies; this model has 24 instruction records.");
d('sched','scheduler',"A queue that waits for dependencies and selects ready operations. The model chooses 16 ALU-side and 12 address-side µop slots; real partitions and policies vary.");
d('wakeup','wakeup','When a µop\'s result is about to be produced, its destination tag is broadcast to the schedulers; waiting µops that need that tag mark the operand ready.');
d('issue','issue / select','Each cycle, each execution port takes the oldest ready µop from its scheduler.');
d('port','execution port','An interface to one or more execution resources. This model chooses four ALU and two address-generation slots per cycle; mapping and sharing are implementation-specific.');
d('alu','ALU','Arithmetic-logic unit: adds, compares, logic, shifts, branch resolution.');
d('agu','AGU','Address generation unit: computes base + index*scale + displacement for loads and stores.');
d('bypass','bypass network','Wires that forward a result straight from a unit\'s output to the next µop\'s input, without a round trip through the register file.');
d('lsu','load/store unit','The part of the core that holds in-flight loads and stores, translates their addresses and accesses the L1d.');
d('lq','load queue',"Tracks loads for ordering, completion and dependency checks. The model chooses 10 entries; actual lifetime, partitioning and capacity differ.");
d('sq','store queue / store buffer',"Tracks store addresses, data and ordering. It supports forwarding and delayed publication. This model chooses eight entries and in-order store commit; other contracts and implementations differ.");
d('sta','store-address µop','The half of a store that computes the address (on an AGU) and writes it into the store-queue entry.');
d('std','store-data µop','The half of a store that delivers the value to be stored into the store-queue entry.');
d('stlf','store-to-load forwarding','A load may obtain bytes from an older buffered store before that store reaches the cache. Byte coverage, available data, size/alignment support and address disambiguation determine whether forwarding is possible; an address match alone is not sufficient.');
d('disamb','memory disambiguation','Deciding whether a load may run before older stores whose addresses are still unknown. Hardware predicts \'no overlap\' and replays the load if that turns out wrong.');
d('retire','retire','The in-order step where a finished instruction\'s results become architectural state: its old physical registers are freed and its store becomes eligible to commit.');
d('commit','store commit','Writing a retired store from the store queue into the L1d. Only here does the store become visible to other cores.');
d('senior','senior store','A store that has retired but still sits in the store queue waiting to commit. It must still forward to younger loads.');
d('squash','squash / flush','Discarding every instruction younger than a mispredicted branch (or a faulting instruction): their ROB, scheduler, queue entries and physical registers are released.');
d('mispredict','misprediction','The branch predictor guessed wrong. Detected when the branch executes; costs the refill time of the front end \u2014 tens of cycles, and directly measurable with a branch-heavy loop over sorted vs. random data.');
d('spec','speculative execution','Executing instructions before it is known that they are on the correct path. Their effects stay inside the core until retirement.');
d('smt','SMT',"Simultaneous multithreading: multiple architectural hardware threads share one core’s resources. Support, thread count and resource partitioning depend on the processor.");
d('ipc','IPC','Instructions retired per cycle.');
d('mab','MAB / MSHR','Miss address buffer (AMD) / miss status holding register: one entry per outstanding cache-line miss. Later misses to the same line merge into the existing entry.');
/* --- cache vocabulary --- */
d('line','cache line',"The unit of cache allocation and coherence in a particular hierarchy. Most examples here choose 64 bytes; inspect the actual cache line and coherence granularity.");
d('set','set','The group of lines an address\'s index bits select. An address can live only in its own set.');
d('way','way','One slot within a set. An 8-way cache has 8 places per set for any given index.');
d('tag','tag','The upper address bits stored with a line so a lookup can confirm which memory block occupies that slot.');
d('index','index','The address bits that select a set.');
d('offset','offset',"The bits selecting a byte within a block. A chosen 64-byte line uses six offset bits.");
d('hit','hit','The requested line is present in that cache level.');
d('miss','miss','The requested line is not present; the request goes to the next level.');
d('valid','valid bit','Marks whether a way holds a real line. A tag match counts only if valid = 1.');
d('dirty','dirty bit','Marks that a line was written after it was filled, so the next level holds a stale copy.');
d('wbk','write-back','A write updates only the cache line and sets its dirty bit; the next level is updated only when the line is evicted.');
d('wthru','write-through','Every write is also sent to the next level immediately.');
d('walloc','write-allocate','On a write miss, the line is first fetched into the cache, then written.');
d('rfo','RFO','Read for ownership: fetching a line with exclusive permission because the core intends to write it. Other cached copies are invalidated.');
d('evict','eviction','Removing a line from a full set to make room. A dirty victim must be written back first.');
d('plru','pseudo-LRU','A cheap approximation of least-recently-used replacement: a small binary tree of bits per set that points toward the older half at each level.');
d('waypred','way predictor (\u00b5tag)',"Historical implementation example: Lipp et al. (Take A Way, 2020) studied virtual-address-based L1D way prediction on tested AMD processors, including Zen and Zen+. This does not establish the predictor of a later generation.");
d('vipt','VIPT','Virtually indexed, physically tagged: the L1 set is chosen with virtual-address bits while the TLB translates in parallel; the tag compare uses the physical address. Works because bits 11:6 are inside the 4 KB page offset and never change in translation.');
d('incl','inclusive cache',"An inclusion contract requires upper-level data to also exist in a lower-level cache. Data inclusion and directory tracking are separate choices. The walkthrough chooses inclusive L2.");
d('victimc','victim cache',"A cache receiving blocks evicted from another level. The walkthrough chooses victim-oriented L3 placement; actual admission and duplication policies require implementation evidence.");
d('shadow','shadow tags',"Metadata tracking which upper caches may hold a line. This lab chooses perfect holder knowledge; proprietary directories can have finite capacities and different encodings.");
d('pfilter','probe filter',"A mechanism narrowing coherence probes using holder information. The teaching model has perfect directory knowledge; absence of LLC data does not prove absence of a private copy.");
d('ccx','CCX',"AMD core-complex terminology for a cache-sharing group. Group size and package organization vary by generation; inspect the named processor rather than assuming the historical four-core arrangement.");
d('mlp','memory-level parallelism',"Memory-level parallelism: several outstanding accesses can overlap. Scaling stops at a finite resource or service boundary. A plateau alone does not reveal a proprietary buffer capacity.");
d('ltu','load-to-use latency','Cycles from a load issuing to the first cycle a dependent instruction can use its value.');
d('wset','working set','The set of addresses a program actively uses during some interval.');
d('sloc','spatial locality','The tendency to access addresses near recently accessed ones.');
d('tloc','temporal locality','The tendency to access the same address again soon.');
d('sram','SRAM','Static RAM: 6 transistors per bit, fast, no refresh. Caches and register files are SRAM.');
d('dramcell','DRAM cell','One transistor plus one capacitor per bit (1T1C). Dense and cheap, but reading drains the capacitor and charge leaks, so rows need restoring and periodic refresh.');
/* --- translation --- */
d('va','virtual address','The address a program uses. 48 bits wide on x86-64 with 4-level paging.');
d('pa','physical address','The address actually sent to caches and DRAM after translation.');
d('page','page',"A mapping granule chosen by the ISA, implementation and OS. The x86-64 example uses 4 KiB base pages; huge mappings and AArch64 granules are separately scoped.");
d('vpn','VPN','Virtual page number: the virtual address with its page-offset bits removed.');
d('pfn','PFN','Page frame number: the physical page number a VPN maps to.');
d('mmu','MMU','Memory management unit: the TLBs, page walkers and permission checks that turn virtual addresses into physical ones.');
d('tlb','TLB','Translation lookaside buffer: a cache of recent VPN-to-PFN translations plus permission bits.');
d('dtlb','DTLB',"Data translation lookaside buffer: caches translations and permissions. Number of levels, entries, associativity and page-size coverage vary. The reach table uses hypothetical counts.");
d('pte','PTE',"Page-table entry: a mapping or next-level descriptor with permissions and attributes. The four-level x86-64 example uses eight-byte entries; format is ISA-specific.");
d('pml4','PML4 / PDPT / PD / PT','The four page-table levels on x86-64. Each is one 4 KB page of 512 eight-byte entries, indexed by 9 bits of the virtual address.');
d('cr3','CR3',"x86 control register identifying the page-table root, with PCID when enabled. Other ISAs name and organize address-space state differently.");
d('walk','page walk','Reading the page-table entries level by level to translate an address after a TLB miss. Each step is a real memory load that goes through the data caches.');
d('pwc','page-walk cache',"Page-walk cache: retains intermediate translation information so a walk can skip work. Capacity, coverage and invalidation require implementation-specific evidence.");
d('reach','TLB reach','How much memory the TLB can map at once: entries × page size. 64 × 4 KB = 256 KB for the L1 DTLB.');
d('huge','huge page','A 2 MB (or 1 GB) page. One TLB entry covers 512× (or 262144×) more memory, and the walk ends one (or two) levels early.');
d('pcid','PCID','Process-context identifier: a 12-bit tag on TLB entries so switching CR3 need not flush every translation.');
d('pf','page fault',"A translation or permission fault handled by the OS. In the x86 walkthrough, exception #PF is vector 14 and CR2 records the address; other ISAs differ.");
d('ftouch','first-touch','Linux\'s default NUMA policy: a page is physically allocated on the node of the CPU that first writes it, not the one that called malloc.');
/* --- fabric, DRAM, I/O --- */
d('fabric','interconnect / fabric',"An interconnect carrying requests, responses and, when supported, coherence traffic. Meshes, rings, chiplet links and centralized attachments create different placement and contention boundaries.");
d('umc','UMC','Unified memory controller: queues memory requests, schedules DRAM commands, enforces timing rules, and performs refresh.');
d('channel','memory channel',"A memory interface with its own service resources. The DDR4 illustration uses two 64-bit channels; DDR5 subchannels and other memory systems have different organization.");
d('dimm','DIMM / rank','A memory module. A rank is the set of chips that together drive the 64-bit bus (8 chips × 8 bits).');
d('bank','bank / bank group','An independent cell array inside each DRAM chip. DDR4 x8 chips have 16 banks in 4 bank groups; different banks can work in parallel.');
d('row','row / column','A bank is a matrix of rows × columns. A whole row is opened at once; reads then select columns from it.');
d('rowbuf','row buffer','The bank\'s sense amplifiers after ACT: they hold the open row. Reads from the open row are fast; any other row needs PRE + ACT first.');
d('act','ACT / RD / WR / PRE / REF','DRAM commands: activate (open a row into the row buffer), read, write, precharge (close the row), refresh.');
d('tcl','CL, tRCD, tRP, tRAS','DRAM timings: CL = RD to first data; tRCD = ACT to RD; tRP = PRE to next ACT; tRAS = ACT to PRE minimum.');
d('burst','burst','One DDR4 read transfers 8 beats on the 64-bit bus: 8 × 8 bytes = 64 bytes, exactly one cache line.');
d('refresh','refresh','Rewriting every row before its capacitors leak. DDR4 issues REF about every 7.8 µs and covers every row within 64 ms.');
d('pcie','PCIe','The serial point-to-point link to devices such as the NVMe SSD. Traffic travels as packets called TLPs.');
d('tlp','TLP','Transaction-layer packet on PCIe: memory read (non-posted, answered by a completion with data), memory write (posted, no reply), message, etc.');
d('rc','root complex','The CPU-side end of PCIe that turns core and fabric requests into TLPs and device TLPs into memory requests.');
d('mmio','MMIO','Memory-mapped I/O: device registers appear at physical addresses; ordinary loads and stores to them reach the device instead of DRAM.');
d('bar','BAR','Base address register: tells the system where a PCIe device\'s MMIO registers sit in the physical address space.');
d('doorbell','doorbell','An MMIO register the driver writes to tell a device that new work is in a queue.');
d('dma','DMA','Direct memory access: a device reads or writes host memory itself, without the CPU copying each byte.');
d('iommu','IOMMU','An MMU for devices: translates device-visible addresses (IOVAs) to physical addresses and blocks access outside what the OS mapped.');
d('iova','IOVA','I/O virtual address: the address a device uses for DMA when an IOMMU is enabled.');
d('msix','MSI-X','Message-signaled interrupts: a device raises an interrupt by writing a small message to a special address the interrupt controller watches.');
d('nvme','NVMe','The SSD protocol built around memory-resident submission and completion queues plus doorbell registers. io_uring was designed around the same ring idea.');
d('iocoh','I/O coherence',"Coherent device access can observe CPU cache data through the platform coherence mechanism. DMA coherency is platform-dependent; drivers use the OS DMA API, including cache maintenance when required.");
/* --- memory types, stores, ordering --- */
d('memtype','memory type',"ISA-defined memory attributes constrain caching, speculation and ordering. The x86 walkthrough uses WB/WT/WC/UC/WP and PAT/MTRR mechanisms; these names and encodings are not universal.");
d('pat','PAT / MTRR','Page attribute table (per-page memory type via PTE bits) and memory type range registers (per physical range). Together they decide the memory type.');
d('wc','write-combining','Stores to WC memory are gathered in a WC buffer and sent out as one full-line write, without reading the line first and without caching it.');
d('nt','non-temporal store','A store hint (movnti, movntdq) that uses write-combining even on WB memory, avoiding the RFO and not polluting the caches.');
d('clflush','clflush / clwb','Instructions that write a line back to memory (clwb keeps it cached; clflush/clflushopt also evict it).');
d('fence','sfence / lfence / mfence','Ordering instructions. mfence waits for the store buffer to drain before later loads run \u2014 tens of cycles, easy to measure with a tight loop of mfence alone.');
d('tso','x86-TSO','x86\'s memory model: every ordering is preserved except a store followed by a load to a different address, which the store buffer can reorder.');
/* --- coherence --- */
d('coh','cache coherence','The guarantee that all cores observe a single order of writes to each address, even though each core has private caches.');
d('moesi','MOESI',"Modified, Owned, Exclusive, Shared and Invalid: conceptual coherence states. This lab chooses a write-invalidate MOESI transaction model with perfect holder tracking; it is not a vendor’s complete protocol.");
d('st_m','M (Modified)','Only this cache has the line and it is dirty. It may be read and written without asking anyone.');
d('st_o','O (Owned)','This cache has a dirty copy and other caches share it. The owner answers requests with data; memory is stale.');
d('st_e','E (Exclusive)','Only this cache has the line and it is clean. A write upgrades it to M silently.');
d('st_s','S (Shared)','Several caches may hold this clean (or owner-backed) copy. A write first needs the others invalidated.');
d('st_i','I (Invalid)','The line is not usable in this cache.');
d('probe','probe / snoop','A coherence message asking another cache to return, downgrade, or invalidate its copy of a line.');
d('fshare','false sharing','Two cores writing different variables that share one 64-byte line. Alternating writers need writable ownership of the same line, so ownership can bounce even though the variables are independent. Repeated writes by a retained owner do not require a new transfer each time.');
/* --- prefetch --- */
d('pref','hardware prefetcher','Logic that watches the stream of miss/access addresses and fetches lines it predicts will be needed, before the program asks.');
d('stream','stream prefetcher','Detects accesses to consecutive lines in one direction and runs ahead along them.');
d('stride','stride prefetcher','Detects a constant distance between successive accesses from the same instruction and fetches ahead by that stride.');
d('swpf','software prefetch','Instructions (prefetcht0/t1/t2/nta) that ask the hardware to start fetching a line without waiting for the data.');
d('late','late prefetch','A prefetch that was issued but whose data had not arrived when the demand access came; the access still waits, but less.');
d('pollute','cache pollution','Useless prefetched lines evicting useful ones.');
d('memwall','memory wall','The widening gap between CPU speed and DRAM latency. The reason the whole hierarchy exists.');
})();
