/* Evidence is scoped to a claim, never inferred from a vendor logo. */
App.Evidence={sources:{
  product:['AMD Ryzen 7 3750H specifications','https://www.amd.com/en/support/downloads/drivers.html/processors/ryzen/ryzen-3000-series/amd-ryzen-7-3750h.html'],
  family:['AMD Family 17h optimization guide 55723, revision 3.01','https://docs.amd.com/v/u/en-US/55723_3.01'],
  measurements:['7-cpu Zen observations and reference notes','https://www.7-cpu.com/cpu/Zen.html'],
  tso:['x86-TSO: A Rigorous and Usable Programmer’s Model','https://www.cl.cam.ac.uk/~pes20/weakmemory/cacm.pdf'],
  intel:['Intel SDM Volume 3A, memory-ordering examples (2024 edition)','https://cdrdv2-public.intel.com/812386/253668-sdm-vol-3a.pdf'],
  arm:['Arm: using the memory-model tool','https://developer.arm.com/community/arm-community-blogs/b/architectures-and-processors-blog/posts/how-to-use-the-memory-model-tool'],
  armbarrier:['Arm: barriers, dependencies and acquire/release litmus tests','https://developer.arm.com/community/arm-community-blogs/b/architectures-and-processors-blog/posts/generate-litmus-tests-automatically-diy7-tool'],
  armmodel:['AArch64 memory-model research and litmus tests','https://www.cl.cam.ac.uk/~sf502/AArch64/'],
  granule:['Arm memory management guide 101811, translation granules','https://developer.arm.com/-/media/Arm%20Developer%20Community/PDF/Learn%20the%20Architecture/LearnTheArchitecture-MemoryManagement-101811_0100_00_en.pdf'],
  cache:['Intel: Xeon cache-hierarchy changes','https://www.intel.com/content/www/us/en/support/articles/000027820/processors/intel-xeon-processors.html'],
  c11:['C11 committee draft N1570, sections 5.1.2.4 and 7.17','https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf']
},claims:[
  {kind:'Documented fact',claim:'Ryzen 7 3750H / Picasso: four cores, eight threads; 384 KB aggregate L1, 2 MB aggregate L2, 4 MB L3.',scope:'This exact product. Aggregate capacity is not a per-thread allocation.',why:'Anchor cache footprints and distinguish an SMT sibling from another core.',source:'product'},
  {kind:'Documented fact',claim:'Two memory channels, up to 2400 MT/s; base 2.3 GHz and boost up to 4 GHz.',scope:'Product limits; DIMM population, firmware, power and workload determine actual operation.',why:'The 38.4 GB/s two-channel peak is arithmetic, not measured sustained bandwidth. A 4 GHz simulator input does not prove the host runs at 4 GHz.',source:'product'},
  {kind:'Measured / reverse-engineered',claim:'External Zen-family notes report simple L1 loads around 4 cycles, Ryzen 2xxx L2 around 12 and random L3 around 35.',scope:'Mixed Zen-family systems and tests on 7-cpu, not a calibration of this 3750H. Cache latency depends on access form and conditions.',why:'Explain the origin and limits of representative configuration defaults; validate the target machine with a controlled sweep.',source:'measurements'},
  {kind:'Inference',claim:'An 8-byte pointer consuming one otherwise unused 64-byte fetched line uses one eighth of those line bytes.',scope:'Only this access/accounting boundary; later reuse can change the useful fraction.',why:'Distinguish useful throughput from transferred cache-line bandwidth.',source:null},
  {kind:'Teaching approximation',claim:'Small queues, LRU policies, serial stages, synthetic addresses and the new labs’ clock values are selected simulation rules.',scope:'Mechanism experiments, not complete Zen+, Intel or Arm implementations.',why:'Change one resource at a time and test the causal explanation without inventing undocumented values.',source:null},
  {kind:'Unknown / implementation-dependent',claim:'The legacy core reference displayed a 44-entry load queue; 7-cpu reports 72 for Zen. The exact 3750H load-queue capacity is not established here.',scope:'Conflicting/insufficient attribution. Neither number is installed as a measured 3750H queue limit.',why:'The actual pipeline model keeps its independent 10-entry teaching queue. Do not derive a hardware saturation threshold from the disputed reference.',source:'measurements'},
  {kind:'Unknown / implementation-dependent',claim:'Legacy 50 L2→L3 / 96 L3→memory limits, exact walker count, SMT quotas, replacement, address hashes and arbitration lack target-specific evidence in this repository.',scope:'Historical family/reference claims are retained with qualifications; no precise 3750H policy is inferred.',why:'Use request/traffic invariants and measured scaling to form hypotheses; occupancy and event definitions need CPU-specific validation.',source:'family'},
  {kind:'Unknown / implementation-dependent',claim:'The old 20.8-TSC-tick branch-misprediction figure has no supporting raw trace or method in this repository.',scope:'Unverified legacy observation; TSC ticks are not automatically core cycles.',why:'Keep a chosen misprediction penalty in the teaching pipeline; measure branch behavior separately before attributing the number to Zen+.',source:null}
]};
