(function(){
  'use strict';
  var U=App.LabUI,h=App.h,s=App.s,M=ControllerLab;
  function build(root){
    var sec=App.labSection(root,'controller','Queues, scheduling and the shared DRAM bus','Compare one request table under different scheduling policies.');
    App.CacheUI.teaching(sec,'This controller enforces a stated subset of DRAM-style timing constraints. All numerical timings are small, chosen model clocks, not DDR4-2400 values or core cycles. Channels have separate command/data buses; ranks on one channel share those buses. Coordinates are supplied explicitly, so no undocumented hardware address hash is invented. The detailed DDR4 device walkthrough above remains the concrete device example.');
    U.checkpoint(sec,'Can serving younger row hits improve total throughput while making an older row-conflict request wait longer?',['Yes, locality and fairness can conflict','No, a faster total means every request improves'],0,'Inspect per-request waiting and bypass counts as well as the completion time. An age rule changes the tradeoff; it is not proof of a bounded hardware latency.');
    var o={channels:1,ranks:1,banks:4,groups:2,readQ:8,writeQ:8,high:6,low:2,policy:'frfcfs',arbitration:'drain',age:80,REFI:0,RFC:24},work={pattern:'locality',spacing:2,writes:25,count:48},custom=false,current=[],r,controls=h('div',{'class':'perf-controls'},sec);
    function knob(key,label,values){U.select(controls,label,values,o[key],function(v){o[key]=isNaN(Number(v))?v:+v;if(key==='banks')o.groups=Math.min(2,o.banks);run();});}
    knob('policy','Controller scheduling',[['fcfs','FCFS: oldest request in the selected queue'],['frfcfs','Ready commands, then row hits, then age']]);
    knob('arbitration','Read/write arbitration',[['arrival','One combined arrival-ordered candidate pool'],['drain','Separate queues with write draining']]);
    knob('channels','Independent channels',[1,2]);knob('ranks','Ranks per channel',[1,2]);knob('banks','Banks per rank',[1,2,4,8]);
    knob('readQ','Read queue entries',[2,4,8,16]);knob('writeQ','Write queue entries',[8,16]);knob('high','Write high watermark',[4,6,8]);knob('low','Write low watermark',[0,2,4]);knob('age','Age override (model clocks; 0 = off)',[0,40,80,160]);
    [['pattern','Generated access pattern',[['locality','Four accesses per open row'],['stream','New rows spread over resources'],['conflict','Alternate rows of one bank']]],['spacing','Arrival spacing (model clocks)',[0,1,2,4,8,16,32]],['writes','Write fraction (%)',[0,25,50,75,100]]].forEach(function(a){U.select(controls,a[1],a[2],work[a[0]],function(v){work[a[0]]=a[0]==='pattern'?v:+v;custom=false;run();});});
    knob('REFI','Refresh interval (0 = off)',[0,64,128,256]);knob('RFC','Refresh busy time',[12,24,40]);
    var advanced=h('details',{'class':'perf-details'},sec);U.text('summary',advanced,'Timing constraints and reduced-model scope');var timed=h('div',{'class':'perf-controls'},advanced);
    [['FAW','Four-activate window',[8,12,24,48]],['WR','Write recovery before precharge',[2,6,12]],['RTW','Read→write data-bus gap',[1,3,8]],['WTRS','Write-data-end→read command, other group',[1,3,5]],['WTRL','Write-data-end→read command, same group',[5,8,12]]].forEach(function(a){o[a[0]]=M.defaults[a[0]];U.select(timed,a[1],a[2],o[a[0]],function(v){o[a[0]]=+v;run();});});
    U.table(advanced,['Constraint','Reduced implementation'],[['tRCD / tRP / tRAS / tRC','ACT→column; PRE→ACT; ACT→PRE; ACT→next ACT on that bank'],['tRRD_S/L and tFAW','Rank-local ACT spacing, and at most four ACTs in the chosen sliding window'],['tCCD_S/L','Column-command spacing; same-group restriction only within one rank'],['tRTP / tWR','Read-command→PRE and end-of-write-data→PRE'],['tWTR_S/L','End of the latest write burst→read command on the same rank'],['Read→write and rank switching','Additional gaps on the shared data bus; deliberately simplified'],['Refresh','Due rank stops new work, finishes prepared requests, precharges and waits for data to drain before REF; no requests use it during RFC']]);
    U.text('p',advanced,'One command per channel per clock. A request reserves its bank between PRE/ACT and its column command to prevent row-opening thrash. FCFS can block ready work behind its oldest request; FR-FCFS-style arbitration chooses among timing-ready commands and favors column commands. Started transactions finish before read/write mode switches. The age override favors old ready requests and old reads at a mode boundary; it is not a strict starvation guarantee. Refresh is scheduled relative to actual REF issue, with simplified rank staggering. This is not a complete JEDEC validator: power states, auto-precharge, all command-pair rules, ECC, PHY/training, address mapping, merging and bounded return queues are omitted.');
    U.text('a',advanced,'Compare a production research simulator: gem5 DRAM controller',{href:'https://gem5.googlesource.com/public/gem5/+/bf238470726b4cc5c0b34fcb349d767726fe53bc/src/mem/DRAMCtrl.py',target:'_blank',rel:'noopener'});
    var editor=h('details',{'class':'perf-details'},sec);U.text('summary',editor,'Edit exact request arrivals and coordinates');U.text('p',editor,'One row per 64-byte request: ID arrival channel rank bank row R|W. Every request addresses a distinct column/line even when the row matches; same-address ordering and memory values are outside this controller model. Arrival is the offered time before bounded-queue admission.');
    var input=h('textarea',{rows:8,'class':'cache-trace-input','aria-label':'Controller request table'},editor),actions=h('div',{'class':'perf-actions'},editor);
    U.text('button',actions,'Apply edited requests',{type:'button'}).onclick=function(){custom=true;run();};U.text('button',actions,'Regenerate requests',{type:'button'}).onclick=function(){custom=false;run();};
    U.text('button',actions,'Five-request audit example',{type:'button'}).onclick=function(){input.value='A 0 0 0 0 3 R\nB 1 0 0 1 9 R\nC 2 0 0 0 3 R\nD 3 0 0 0 7 R\nE 4 0 0 1 9 W';custom=true;run();};
    var status=U.text('p',sec,'',{role:'status'}),metrics=h('div',{'class':'perf-metrics'},sec),explain=h('div',{'class':'perf-explanation'},sec),state=h('div',{'class':'queue-state'},sec),fig=h('figure',{'class':'perf-chart controller-timeline'},sec),svg=s('svg',{viewBox:'0 0 900 260',role:'img','aria-label':'Controller command markers and non-overlapping read and write data bursts'},fig);
    var step=App.CacheUI.replayControls(sec,'Controller clock',function(i){if(!r)return;var snap=r.trace[i];state.replaceChildren();U.text('h3',state,'Clock '+snap.t+' · '+snap.completed+'/'+r.requests.length+' completed');
      U.table(state,['Channel','Read queue','Write queue','Arbitration'],snap.channels.map(function(c,k){return [k,c.read.join(' ')||'empty',c.write.join(' ')||'empty',r.p.arbitration==='arrival'?'combined':c.mode==='R'?'read mode':'write drain'];}));
      var rows=[];snap.channels.forEach(function(c,ci){c.ranks.forEach(function(rank,ri){rank.banks.forEach(function(b,bi){rows.push([ci+' / '+ri+' / '+bi,rank.refreshUntil>snap.t?'refresh until '+rank.refreshUntil:rank.pending?'quiescing for refresh':'available',b.row===null?'closed':'row '+b.row,b.reserved||'none']);});});});U.table(state,['Channel / rank / bank','Rank state','Open row','Prepared request'],rows);
      var now=r.commands.filter(function(c){return c.t===snap.t;});U.text('p',state,'Commands now: '+(now.map(function(c){return c.name+' '+(c.id||'maintenance')+' on ch'+c.channel+'/rank'+c.rank+(c.bank!==null?'/bank'+c.bank:'');}).join(' · ')||'none; timing, policy or idle input prevents issue'));
      timeline(snap.t);
    });
    U.text('figcaption',fig,'80-clock window; scroll horizontally on narrow screens. Upper ticks mark commands (hover for details); lower rectangles are 64-byte data bursts, green reads and violet writes. The same-channel bursts cannot overlap. Separate channels can transfer at once.');
    var latency=h('div',null,sec),detail=h('details',{'class':'perf-details'},sec);U.text('summary',detail,'Per-request latency decomposition and command log');var tables=h('div',null,detail);
    var buttons=h('div',{'class':'perf-actions'},sec),compare=U.text('button',buttons,'Compare both schedulers on this trace',{type:'button'}),sweep=U.text('button',buttons,'Sweep offered load',{type:'button'}),download=U.text('button',buttons,'Export model result JSON',{type:'button'}),comparison=h('div',{'class':'controller-comparison'},sec);
    compare.onclick=function(){if(!r)return;comparison.replaceChildren();var rows=['fcfs','frfcfs'].map(function(policy){var x=M.simulate(current,Object.assign({},o,{policy:policy,trace:false}));return [policy,x.cycles,x.latency.p95,x.readP95===null?'n/a':x.readP95,Math.max.apply(null,x.requests.map(function(q){return q.bypassed;})),x.stats.turnarounds];});U.table(comparison,['Policy','Finish interval','All p95','Read p95','Max bypasses','Direction switches'],rows);U.text('p',comparison,'Both runs use identical arrivals, coordinates, capacities and timing parameters. FCFS applies within the active arbitration pool; write-drain mode is not one global FCFS order.');};
    sweep.onclick=function(){comparison.replaceChildren();var rows=[32,16,8,4,2,1,0].map(function(spacing){var w=Object.assign({},work,o,{spacing:spacing}),x=M.simulate(M.workload(w),Object.assign({},o,{trace:false}));return [spacing,x.bandwidth.toFixed(2),x.latency.mean.toFixed(1),x.latency.p95,x.stats.readQueueFull,x.stats.writeQueueFull];});U.table(comparison,['Arrival spacing','Line B/clock','Mean latency','p95 latency','Read full clocks','Write full clocks'],rows);U.text('p',comparison,'This sweep regenerates the selected pattern, preserving its 48 requests and mix. It does not reuse a manually edited trace. Throughput can saturate while waiting grows. Full-queue counts sum channel-clocks, not stall cycles of a CPU instruction.');};
    download.onclick=function(){if(!r)return;var blob=new Blob([JSON.stringify({schema:'memory-lab-controller-model-v1',evidence:'teaching approximation; not hardware measurement',parameters:r.p,requests:r.requests,commands:r.commands,bursts:r.bursts,stats:r.stats},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=U.text('a',buttons,'',{href:url,download:'controller-model.json'});a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);};
    function timeline(clock){svg.replaceChildren();var start=Math.max(0,clock-20),end=start+80,height=50+r.p.channels*100;svg.setAttribute('viewBox','0 0 900 '+height);function x(t){return 80+(t-start)*10;}
      for(var n=0;n<=8;n++){var tick=start+n*10;s('line',{x1:x(tick),x2:x(tick),y1:20,y2:height-25,'class':'perf-grid'},svg);s('text',{x:x(tick),y:height-7,'text-anchor':'middle','class':'s'},svg,String(tick));}
      for(var channel=0;channel<r.p.channels;channel++){var y=40+channel*100;s('text',{x:4,y:y,'class':'s'},svg,'CH '+channel);s('text',{x:4,y:y+20,'class':'s'},svg,'CMD');s('text',{x:4,y:y+51,'class':'s'},svg,'DATA');}
      r.commands.filter(function(c){return c.t>=start&&c.t<end;}).forEach(function(c){var g=s('g',null,svg);s('title',null,g,c.name+' '+(c.id||'refresh/precharge')+' · clock '+c.t+' · rank '+c.rank+' bank '+c.bank);s('line',{x1:x(c.t),x2:x(c.t),y1:48+c.channel*100,y2:64+c.channel*100,stroke:c.name==='REF'?'var(--bad)':'var(--act)','stroke-width':2},g);});
      r.bursts.filter(function(b){return b.end>start&&b.start<end;}).forEach(function(b){var lo=Math.max(start,b.start),hi=Math.min(end,b.end),g=s('g',null,svg);s('title',null,g,b.id+' '+b.type+' '+b.start+'–'+b.end);s('rect',{x:x(lo),y:72+b.channel*100,width:(hi-lo)*10,height:24,rx:3,'class':b.type==='R'?'a2b':'a3b'},g);if(hi-lo>=3)s('text',{x:x(lo)+3,y:88+b.channel*100,'class':'s'},g,b.id);});s('line',{x1:x(clock),x2:x(clock),y1:18,y2:height-24,'class':'trace-marker'},svg);
    }
    function run(){try{
      if(custom){current=input.value.trim().split(/\n+/).map(function(line){var a=line.trim().split(/[\s,]+/);if(a.length!==7)throw new Error('Each request needs exactly 7 fields.');return {id:a[0],arrival:Number(a[1]),channel:Number(a[2]),rank:Number(a[3]),bank:Number(a[4]),row:Number(a[5]),type:a[6].toUpperCase()};});}
      else{current=M.workload(Object.assign({},work,o));input.value=current.map(function(x){return [x.id,x.arrival,x.channel,x.rank,x.bank,x.row,x.type].join(' ');}).join('\n');}
      r=M.simulate(current,o);sec._controllerResult=r;compare.disabled=false;sweep.disabled=false;download.disabled=false;status.textContent='Simulation · '+(custom?'edited':'generated')+' trace · '+r.requests.length+' requests · all times in model clocks';metrics.replaceChildren();explain.replaceChildren();tables.replaceChildren();latency.replaceChildren();comparison.replaceChildren();
      U.metric(metrics,'Completion interval',r.cycles+' clocks','First offered arrival → final data beat');U.metric(metrics,'Aggregate line bandwidth',r.bandwidth.toFixed(2)+' B/clock',(100*r.busUtil).toFixed(1)+'% of combined data-bus occupancy');U.metric(metrics,'Mean / p95 request latency',r.latency.mean.toFixed(1)+' / '+r.latency.p95,'Offered arrival → final data beat; includes admission wait');U.metric(metrics,'Reads / writes',r.stats.readBytes+' / '+r.stats.writeBytes+' B','Each request moves one 64-byte line');
      U.text('p',explain,'Row hit / closed / conflict at first command: '+r.stats.rowHit+' / '+r.stats.rowClosed+' / '+r.stats.rowConflict+'. Data-bus direction changes: '+r.stats.turnarounds+'. Refresh commands: '+r.stats.refreshes+'. Read p95: '+(r.readP95===null?'no reads':r.readP95+' clocks')+'. A hit row does not eliminate queueing, bus contention or refresh.');
      U.table(latency,['Latency distribution','Mean','p50','p95','p99','Max'],[['All requests',r.latency.mean.toFixed(1),r.latency.p50,r.latency.p95,r.latency.p99,r.latency.max]]);
      U.text('p',latency,'Nearest-rank quantiles of individual simulated requests. Admission wait is arrival→queue admission; queue wait is admission→first command; the command interval is first command→last data and includes further arbitration/timing waits. It is not pure service time or full CPU load-to-use latency. Fabric, translation and cache-return stages are outside this boundary.');
      U.table(tables,['Request / type','Arrival → admit → first → column → done','Row state','Admission / queue / command interval','Bypassed'],r.requests.map(function(q){return [q.id+' '+q.type,[q.arrival,q.admit,q.first,q.column,q.done].join(' → '),q.rowClass,[q.admissionWait,q.queueWait,q.commandInterval].join(' / '),q.bypassed];}));
      U.table(tables,['Clock','Command / request','Channel / rank / bank / row'],r.commands.map(function(c){return [c.t,c.name+' '+(c.id||'maintenance'),[c.channel,c.rank,c.bank===null?'—':c.bank,c.row===null?'—':c.row].join(' / ')];}));step.set(r.trace.length);
    }catch(e){r=null;sec._controllerResult=null;compare.disabled=true;sweep.disabled=true;download.disabled=true;[metrics,explain,tables,latency,comparison,state,svg].forEach(function(el){el.replaceChildren();});status.textContent='Could not run: '+e.message;}}
    run();
    U.text('h3',sec,'Measure loaded latency on your machine');
    U.text('p',sec,'First establish a pinned dependent pointer-chase baseline with a working set beyond the measured cache plateau. Then place independent bandwidth generators on other physical cores and repeat at increasing load, keeping topology, frequency, page policy and thermals recorded. Separate CPU cache/fabric interference from the DRAM-controller inference: a slower chase alone does not identify the controller policy, row hit rate or bank mapping.');
    U.text('p',sec,'Use the native harness and protocol below. Report both chase ns/load and generator useful GB/s. Hardware latency samples and whole-trial averages are different distributions; generic cache-misses is not a DRAM row-miss counter. No browser time here is a hardware measurement.');
    U.text('a',sec,'Runnable hardware measurement protocol',{href:'benchmarks/README.md'});
    measurement(sec);
  }
  function validate(data){
    if(!data||data.schema!=='memory-lab-loaded-v1'||!data.context||typeof data.context!=='object'||Array.isArray(data.context)||!Array.isArray(data.samples)||!data.samples.length||data.samples.length>5000)throw new Error('Expected memory-lab-loaded-v1 with context and 1–5000 samples.');
    data.samples.forEach(function(r){if(!r||['read','write'].indexOf(r.mode)<0||!Array.isArray(r.generators))throw new Error('Invalid loaded-latency case.');['bytes_per_worker','steps','elapsed_ns','chunk_bytes'].forEach(function(k){if(!Number.isSafeInteger(r[k])||r[k]<=0)throw new Error('Invalid '+k);});if(r.bytes_per_worker%65536||r.chunk_bytes!==65536||!Number.isSafeInteger(r.chase_cpu)||r.chase_cpu<0||!Number.isSafeInteger(r.background_threads)||r.background_threads<0||r.background_threads>7||r.generators.length!==r.background_threads)throw new Error('Invalid size or worker accounting.');var cpus=new Set([r.chase_cpu]);r.generators.forEach(function(g){['cpu','chunks_before','chunks_after','useful_bytes'].forEach(function(k){if(!Number.isSafeInteger(g[k])||g[k]<0)throw new Error('Invalid generator '+k);});if(cpus.has(g.cpu)||g.chunks_after<g.chunks_before||g.useful_bytes!==(g.chunks_after-g.chunks_before)*65536)throw new Error('Invalid generator placement or byte accounting.');cpus.add(g.cpu);});});return data;
  }
  function measurement(sec){
    U.code(sec,'python3 benchmarks/run_all.py --serve\n# Individual fallback: python3 benchmarks/loaded.py --cpus 0,2,4,6 --output loaded-results.json');
    U.text('p',sec,'This harness warms and validates a randomized dependent ring, then adds zero through N pinned read/write generators. Each worker allocates and first-touches its own memory after pinning. The chase starts after every generator has completed a full pass. Generator progress is counted in 64 KiB chunks around the chase interval: its useful bandwidth is approximate and includes boundary quantization. The chase timer covers the dependent kernel, not setup or joins.');
    var label=h('label',{'class':'perf-field'},sec);U.text('span',label,'Import loaded-latency result JSON');var input=h('input',{type:'file',accept:'.json,application/json','aria-label':'Loaded latency result JSON'},label),status=U.text('p',sec,'No loaded-latency hardware results loaded.',{role:'status','class':'loaded-status'}),out=h('div',{'class':'loaded-results'},sec);
    function render(data,label){validate(data);if(label)U.text('h3',out,label,{'class':'measurement-run-title'});var groups={};data.samples.forEach(function(r){var key=[r.chase_cpu,r.bytes_per_worker,r.background_threads,r.mode].join(' / ');(groups[key]||(groups[key]=[])).push(r);});
      status.textContent='Measured data · '+String(data.context.cpu_model||'unknown CPU')+' · '+(data.complete===true?'complete run':'partial / completion not recorded');
      U.table(out,['Chase CPU / bytes per worker / generators / mode','Trials','Median chase ns/load','p95 of trial ns/load','Median generator useful GB/s (approx.)'],Object.keys(groups).sort().map(function(k){var rows=groups[k],ns=rows.map(function(r){return r.elapsed_ns/r.steps;}),bw=rows.map(function(r){return r.generators.reduce(function(n,g){return n+g.useful_bytes;},0)/r.elapsed_ns;});return [k,rows.length,MeasurementBundle.stats(ns).median.toFixed(2),LabModel.quantile(ns,.95).toFixed(2),MeasurementBundle.stats(bw).median.toFixed(2)];}));
      U.text('p',out,'These are real whole-trial measurements with the supplied context. They do not identify row policy, queue size, individual-load tails or DRAM-bus bytes. A small working set may measure cache contention instead of external-memory contention; establish the working-set plateau first.');var details=h('details',null,out);U.text('summary',details,'Original loaded-latency context');U.code(details,JSON.stringify(data.context,null,2));
    }
    input.onchange=async function(){out.replaceChildren();try{var f=input.files[0];if(!f)return;if(f.size>2*1024*1024)throw new Error('Maximum file size is 2 MiB.');render(JSON.parse(await f.text()),'Manual import · locally read, not uploaded');}catch(e){status.textContent='Could not import: '+e.message;}};
    App.Measurements.bind('loaded',status,out,render);
  }
  App.extendChapter('dram',build);
  App.ControllerUI={validate:validate};
})();
