(function(){
  'use strict';
  var U=App.LabUI,h=App.h,s=App.s,M=ArchitectureLab,E=App.Evidence;
  function source(root,key){var q=E.sources[key];return U.text('a',root,q[0],{href:q[1],target:'_blank',rel:'noopener'});}
  function sources(root,keys){var p=U.text('p',root,'Sources: ');keys.forEach(function(k,i){if(i)U.text('span',p,' · ');source(p,k);});}
  function section(root,id,title,copy){return App.labSection(root,id,title,copy);}
  function reference(root){var sec=section(root,'reference','Why implementations differ','A mechanism suggests a question; evidence determines the scope of an answer.');
    U.badge(sec,'Architecture-neutral mechanisms · scoped implementation choices');U.text('p',sec,'No processor is the lab’s universal reference. The finite models expose dependencies, allocation, contention and visibility. Modern case studies below identify the exact implementation, evidence and experiment; missing proprietary details remain unknown.');
    var ctl=h('div',{'class':'perf-controls'},sec),filter='all';U.select(ctl,'Evidence category',[['all','All evidence'],...ImplementationEvidence.categories.map(function(k){return [k,k];})],filter,function(v){filter=v;draw();});var out=h('div',{'class':'evidence-claims'},sec);
    function draw(){out.replaceChildren();E.claims.filter(function(q){return filter==='all'||q.kind===filter;}).forEach(function(q){var card=h('div',{'class':'evidence-contract'},out);U.text('span',card,q.kind,{'class':'evidence-label evidence-kind','data-evidence-kind':q.kind});U.text('h3',card,q.claim);U.text('p',card,q.scope);U.text('p',card,'Why it matters: '+q.why);if(q.source)source(card,q.source);});}draw();
    U.text('h3',sec,'Choose comparisons by their consequence');U.table(sec,['Mechanism','Implementation choice','Experiment / evidence'],[['Visibility and ordering','Instruction and memory-attribute contracts, separate from internal speculation','Ordinary x86 WB / selected AArch64 contrasts → Stores ordering lab'],['Private and shared copies','Data inclusion, placement and directory tracking are separate choices','Hierarchy inclusion experiment; historical cache-policy contrast'],['Translation','Supported granules, page formats and actual OS mappings','x86-64 walkthrough / AArch64 granule geometry'],['Topology and concurrency','Cache sharing domain, memory attachment and OS NUMA nodes','EPYC 9005 / Xeon 6 topology cases; native loaded latency'],['Evidence boundary','Core IP documentation versus the surrounding server SoC','Neoverse V3 core scope and unified-cache telemetry']]);
    U.text('p',sec,'A shared ISA does not imply equal queue sizes, policies or performance. A comparison earns space when it changes allowed outcomes, resource contention, placement or measurement interpretation. Published evidence never silently fills a simulator parameter.');
    U.text('a',sec,'Measure your machine with recorded topology and environment →',{href:'#perf/datasets'});
  }
  function ordering(root){var sec=section(root,'litmus','Ordering: guarantees, outcomes and witnesses','Coherence orders one location; a memory model constrains relationships across locations.');
    U.table(sec,['Layer','Question it answers','What it does not establish'],[['Language','Are accesses atomic, race-free and connected by happens-before?','A C/C++ data race cannot be repaired by a claim about x86 hardware.'],['Compiler','Which instructions and dependencies implement the language program?','volatile or a compiler barrier alone is not inter-thread synchronization.'],['ISA memory model','Which architectural observations are allowed for these instructions and memory attributes?','It does not specify cache latency, queue partitioning or a cycle schedule.'],['Microarchitecture','How do speculation, replay, buffers and coherence implement the contract?','An internally early load need not become an architecturally forbidden observation.'],['Cache coherence','How are copies and writes to a location kept consistent?','Per-location coherence alone does not provide the ordering of independent x and y.']]);
    App.CacheUI.teaching(sec,'The x86-TSO illustration has an in-order instruction stream per hardware thread, FIFO store publication and forwarding from its own youngest matching store. SC publishes each store immediately. The relaxed illustration can issue independent operations in either order; it explains these selected Arm-style contrasts but is not a complete AArch64 axiomatic model. All accesses are aligned ordinary coherent memory. Device/WC/NT accesses, atomics, mixed sizes, dependencies, exceptions and speculative implementation timing are outside this engine.');
    U.checkpoint(sec,'Two threads each store 1, then load the other location. Can both loads return 0 on ordinary x86 write-back memory?',['Yes: each store can still be buffered','No: coherent caches force sequential consistency'],0,'Step the 0,0 witness. The stores eventually become visible; coherence is preserved throughout.');
    var o={name:'SB',model:'tso',fenced:false},ctl=h('div',{'class':'perf-controls'},sec);
    U.select(ctl,'Litmus case',[['SB','Store Buffering'],['MP','Message Passing'],['LB','Load Buffering']],o.name,function(v){o.name=v;run();});
    U.select(ctl,'Ordering rules',[['tso','x86-TSO illustration (AMD / Intel ordinary WB)'],['relaxed','Relaxed illustration (selected Arm contrasts)'],['sc','Sequential consistency']],o.model,function(v){o.model=v;run();});
    U.select(ctl,'Full ordering points',[[0,'None'],[1,'Between the two operations on both threads']],0,function(v){o.fenced=!!+v;run();});
    var program=h('div',{'class':'ordering-program'},sec),metrics=h('div',{'class':'perf-metrics'},sec),summary=U.text('p',sec,''),choices=h('div',{'class':'perf-controls'},sec),state=h('div',{'class':'cache-state ordering-state'},sec),trace,r;
    var step=App.CacheUI.replayControls(sec,'Ordering event',function(i){if(!trace)return;var e=trace[i],q=e.state;state.replaceChildren();U.text('h3',state,'Event '+i+' · '+e.label);U.table(state,['Hardware thread','Issued operations (program positions)','Pending store publication'],q.issued.map(function(a,cpu){return ['T'+cpu,a.map(function(v,k){return (k+1)+': '+(v?'issued':'waiting');}).join(' / '),q.buffers[cpu].map(function(w){return w.addr+'='+w.value;}).join(' → ')||'empty'];}));U.table(state,['Shared memory x / y','Read registers r0 / r1'],[[q.memory.x+' / '+q.memory.y,[q.registers.r0,q.registers.r1].map(function(x){return x===null?'not read':x;}).join(' / ')]]);});
    function opText(op){return op.kind==='F'?'full ordering point':op.kind==='W'?'store '+op.addr+' = 1':'load '+op.addr+' → '+op.reg;}
    function run(){r=M.litmus(o);sec._orderingResult=r;program.replaceChildren();metrics.replaceChildren();choices.replaceChildren();U.table(program,['Program position','Thread 0','Thread 1'],r.programs[0].map(function(op,i){return [i+1,opText(op),opText(r.programs[1][i])];}));U.metric(metrics,'Target outcome',r.target,'r0, r1; initially x = y = 0');U.metric(metrics,'Target reachable',r.targetAllowed?'Yes':'No','Under exactly the selected reduced rules');U.metric(metrics,'Distinct outcomes / states',Object.keys(r.outcomes).length+' / '+r.states,'Enumeration counts are not outcome probabilities');
      var key=r.targetAllowed?r.target:Object.keys(r.outcomes)[0];U.select(choices,'Witness outcome',Object.keys(r.outcomes).sort(),key,function(v){trace=r.outcomes[v].trace;step.set(trace.length);});trace=r.outcomes[key].trace;step.set(trace.length);
      summary.textContent=o.fenced?'A full point on both threads removes the highlighted weak outcome in these tests. x86 MFENCE and Arm DMB SY are relevant counterparts for the selected ordinary-memory cases; the model does not simulate their execution costs.':o.name==='SB'?'TSO allows 0,0 because local publication can lag a later independent read. AMD and Intel x86 need the same relevant correctness prediction here.':o.name==='MP'?'For x86 WB, observing y=1 after the writer’s x=1 then y=1 forces the later reader load of x to see 1 in this two-thread test. Plain AArch64 message passing permits y=1,x=0; order publication and consumption explicitly.':'The stores here write constant 1, independent of the earlier reads. The relaxed witness issues them early; the 1,1 result is forbidden by TSO but permitted in the selected AArch64 LB contrast. Adding data/control dependencies changes the test and needs the actual ISA model.';
    }run();
    var language=section(root,'language','Translate the guarantee into a language program','A hardware witness is not permission to write a data-racing C program.');
    var kind='release',seen=1,controls=h('div',{'class':'perf-controls'},language);U.select(controls,'Publication in C11',[['release','Release flag / acquire flag'],['relaxed','All data and flag accesses atomic, relaxed'],['plain','Non-atomic data and non-atomic flag'],['seqcst','All data and flag accesses atomic, seq_cst']],kind,function(v){kind=v;explain();});U.select(controls,'Value read from flag',[0,1],1,function(v){seen=+v;explain();});var code=h('div',null,language),verdict=U.text('p',language,'',{role:'status'});
    function explain(){code.replaceChildren();var order=kind==='seqcst'?'memory_order_seq_cst':kind==='release'?'memory_order_release':'memory_order_relaxed',readOrder=kind==='release'?'memory_order_acquire':order;
      U.code(code,kind==='plain'?'// Intentionally invalid synchronization: do not use.\n// Initially data = 0, flag = 0.\n// Producer                 // Consumer\ndata = 42;                  if (flag == 1)\nflag = 1;                       use(data);':'// Objects initialized before starting threads; one publication only.\n// Producer\n'+(kind==='release'?'data = 42; // non-atomic payload':'atomic_store_explicit(&data, 42, '+order+');')+'\natomic_store_explicit(&flag, 1, '+order+');\n\n// Consumer\nif (atomic_load_explicit(&flag, '+readOrder+') == 1)\n    use('+(kind==='release'?'data':'atomic_load_explicit(&data, '+order+')')+');');
      verdict.textContent=kind==='plain'?'The concurrent non-atomic flag accesses create a C11 data race. This program has undefined behavior; there is no valid C outcome histogram to compare with the hardware model.':seen===0?'The condition is false: the consumer does not read the payload. An acquire that reads the initial 0 does not synchronize with the producer’s release of 1.':kind==='relaxed'?'Every object is atomic, so the accesses shown avoid a data race, but relaxed operations do not publish an ordering between the two objects. The language permits flag=1 with old data. A particular compiler/ISA can implement a stronger subset.':'The reader sees the producer’s published 1. In this one-publication example, the ordering guarantees require data=42. For release/acquire, that reads-from relationship creates synchronization and makes the non-atomic payload access race-free. Reusing the flag/payload requires a separate lifetime/ownership protocol.';
    }explain();sources(language,['c11','armbarrier']);
    U.text('h3',sec,'Check a formal model, then observe real hardware');U.text('p',sec,'Use herd7 with the exact architecture model and litmus source, retaining tool/model versions. litmus7 can run the case on supported native hardware; record trials, compiler output, CPU placement and forbidden/allowed outcomes. Failure to observe an allowed result does not make it forbidden. QEMU user-mode or a browser timing loop is not a memory-ordering measurement of an Arm CPU.');U.text('a',sec,'Reproducible litmus sources and protocol',{href:'benchmarks/litmus/README.md'});sources(sec,['tso','intel','arm','armmodel']);
  }
  function inclusion(root){var sec=section(root,'inclusion','Inclusion is a constraint on copies','One core can lose a hot private line because another core pressures a shared inclusive cache.');
    App.CacheUI.teaching(sec,'Two private read-only caches and one shared LLC use fully associative LRU. Inclusive duplicates each fill and back-invalidates upper copies on LLC eviction. Exclusive moves data between the LLC and the private-cache union (private cores may share a line). The chosen NINE policy fills both levels, allows duplicates, and permits an LLC eviction to leave private copies intact. NINE means neither inclusive nor exclusive; it does not prescribe this particular allocation policy. No dirty traffic or finite directory is modeled.');
    U.checkpoint(sec,'Thread 0 repeatedly uses A in its private cache. Thread 1 evicts A’s shared LLC entry. Must thread 0 lose A?',['Only if the chosen inclusion contract requires it','Always: coherence requires every cache to hold A'],0,'Compare the same reference trace. An LLC data miss does not prove no private cache has the line.');
    var o={policy:'inclusive',privateLines:2,llcLines:4},ctl=h('div',{'class':'perf-controls'},sec);U.select(ctl,'LLC inclusion policy',[['inclusive','Inclusive'],['exclusive','Exclusive data / victim-style'],['nine','Neither inclusive nor exclusive']],o.policy,function(v){o.policy=v;run();});U.select(ctl,'Private cache lines',[1,2,4],2,function(v){o.privateLines=+v;run();});U.select(ctl,'Shared LLC lines',[2,4,8],4,function(v){o.llcLines=+v;run();});var lab=h('label',{'class':'perf-field'},sec);U.text('span',lab,'Read trace (thread:line; A=0, B=1…)');var input=h('textarea',{rows:2,'class':'cache-trace-input','aria-label':'Inclusion read trace'},lab);input.value='0:A 1:B 1:C 1:D 1:E 0:A 1:F 0:A';var actions=h('div',{'class':'perf-actions'},sec);U.text('button',actions,'Apply inclusion trace',{type:'button'}).onclick=run;
    var status=U.text('p',sec,'',{role:'status'}),metrics=h('div',{'class':'perf-metrics'},sec),state=h('div',{'class':'cache-state'},sec),r,step=App.CacheUI.replayControls(sec,'Inclusion reference',function(i){if(!r)return;var e=r.trace[i];state.replaceChildren();U.text('h3',state,'T'+e.cpu+' reads line '+e.line+' · '+e.where);U.text('p',state,e.events.join(' → ')||'Private hit changes its own LRU order; it does not refresh the LLC.');U.table(state,['Location','Data lines (MRU → LRU)'],[['T0 private',e.upper[0].join(' → ')||'empty'],['T1 private',e.upper[1].join(' → ')||'empty'],['LLC',e.lower.join(' → ')||'empty']]);U.text('p',state,e.unique+' distinct data lines; '+e.duplicates+' duplicate data slots. Directory/tag metadata is not counted as data capacity.');});
    function run(){try{var access=input.value.trim().split(/[\s,]+/).map(function(t){var m=/^([01]):([A-Z]|\d+)$/i.exec(t);if(!m)throw new Error('Use thread 0 or 1, a colon, and A–Z or a line number.');return {cpu:+m[1],line:/^[a-z]$/i.test(m[2])?m[2].toUpperCase().charCodeAt(0)-65:+m[2]};});r=M.inclusion(access,o);sec._inclusionResult=r;status.textContent='';metrics.replaceChildren();U.metric(metrics,'Private / peer / LLC hits',r.stats.privateHits+' / '+r.stats.peerHits+' / '+r.stats.llcHits,'Same demand trace for each policy');U.metric(metrics,'Memory reads',r.stats.memoryReads+' lines',r.bytes+' B, not a cycle prediction');U.metric(metrics,'Back-invalidations',String(r.stats.backInvalidations),'Private lines removed by LLC inclusion');step.set(r.trace.length);}catch(e){r=null;sec._inclusionResult=null;state.replaceChildren();metrics.replaceChildren();status.textContent=e.message;}}run();
    U.table(sec,['Concrete scope','Evidence and consequence'],[['Historical AMD Zen+ (2018)','The historical Family 17h description motivates a victim-oriented contrast; it is not the strict exclusive toy rule. It does not establish the policy of a modern EPYC CCD.'],['Historical Intel E5 v4 versus Skylake-SP','Intel documents inclusive LLC for the older E5 v4 hierarchy and a shift to non-inclusive LLC in Xeon Scalable. That changes the requirement to duplicate private-cache data; it does not eliminate coherence tracking.'],['Any architecture','An absent LLC data line can still have a directory entry or private owner. Directory inclusion and data inclusion are separate design choices. This lab assumes perfect knowledge of private holders.']]);U.text('p',sec,'Measurement: pin a hot reader and an independent cache-pressure workload to known cores, hold the reader’s footprint fixed, and compare latency/misses. LLC size, replacement, set mapping, prefetching and topology also affect the result. Timing alone cannot prove inclusion or an undocumented directory organization.');sources(sec,['cache','family']);
  }
  function granules(root){var sec=section(root,'granules','An Arm lens on translation granules','Page geometry changes reach and simple VIPT indexing constraints.');U.badge(sec,'Documented ISA choice + teaching geometry');U.text('p',sec,'The x86-64 walkthrough chooses four-level tables and 4 KiB pages. AArch64 provides choices among 4, 16 and 64 KiB translation granules; supported choices are implementation-dependent and the OS chooses a supported configuration. This is an ISA/OS distinction, not a claim that every Arm CPU supports every size or has the same TLB. Larger block mappings are separate from the base granule.');
    var o={regions:256,stride:4096,entries:64},cache=32768,ways=8,ctl=h('div',{'class':'perf-controls'},sec);U.select(ctl,'Granule access stride',[[4096,'One word every 4 KiB'],[65536,'One word every 64 KiB']],4096,function(v){o.stride=+v;draw();});U.select(ctl,'Equal model TLB entries',[16,64,128],64,function(v){o.entries=+v;draw();});U.select(ctl,'Hypothetical VIPT data-cache bytes',[32768,65536,131072],cache,function(v){cache=+v;draw();});U.select(ctl,'Hypothetical VIPT ways',[4,8,16],ways,function(v){ways=+v;draw();});var out=h('div',null,sec);
    function draw(){out.replaceChildren();var rows=[4096,16384,65536].map(function(size){var q=M.granule(Object.assign({},o,{pageBytes:size}));return [size+' B',q.reach+' B',q.misses+' / 512',q.mappedBytes+' B',cache/ways<=size?'Fits unchanged page-offset bits':'Needs alias/index handling beyond this simple rule'];});sec._granuleRows=rows;U.table(out,['Base granule','Model TLB reach','Misses / accesses','Whole-mapping footprint','Simple VIPT set+offset geometry'],rows);U.text('p',out,'For a conventional power-of-two VIPT index using only unchanged page-offset bits, capacity ÷ ways ≤ page bytes. Here capacity ÷ ways = '+cache/ways+' B. This is a geometry constraint, not a ban on larger real caches: physical indexing, alias handling, prediction or other implementations can change the design.');}draw();
    U.text('p',sec,'The TLB model deliberately keeps entries and LRU replacement equal to isolate page geometry. Two dense passes can need fewer translations with a larger granule; sparse accesses may pay a larger mapped footprint with less benefit. Query the actual OS page size, mapping state and CPU support before moving results between machines. The 32 KiB / 8-way / 4 KiB combination is the chosen teaching geometry in the L1 data walkthrough.');sources(sec,['granule']);
  }
  function compare(root){var sec=section(root,'compare','Compare measurements without inventing a machine','Import two native runs and keep the experimental conditions attached.');U.badge(sec,'Measured data only when supplied');U.text('p',sec,'For optional measured-machine / visitor comparison, open Results. This optional fallback accepts two memory-lab-v1 runs from the native harness. Cases join only when recorded clock/byte/timing boundaries, mode, total bytes, chain count, steps, operation count and seed match. A time ratio describes those runs; it does not isolate the ISA or prove a specific queue size.');var data=[null,null],ctl=h('div',{'class':'perf-controls'},sec),status=U.text('p',sec,'Load both runs to compare measured values.',{role:'status','class':'comparison-status'}),out=h('div',{'class':'architecture-comparison'},sec);
    [0,1].forEach(function(i){var label=h('label',{'class':'perf-field'},ctl);U.text('span',label,'Native run '+(i?'B':'A'));var input=h('input',{type:'file',accept:'.json,application/json','aria-label':'Architecture run '+(i?'B':'A')},label);input.onchange=async function(){try{var file=input.files[0];if(!file)return;if(file.size>2*1024*1024)throw new Error('Maximum file size is 2 MiB.');data[i]=App.Performance.validateMeasurement(JSON.parse(await file.text()));draw();}catch(e){data[i]=null;out.replaceChildren();status.textContent='Could not compare: '+e.message;}};});
    function draw(){out.replaceChildren();if(!data[0]||!data[1]){status.textContent='One run loaded; supply the other run.';return;}var matched=['clock','timing_boundary','useful_byte_boundary'].every(function(k){return typeof data[0].context[k]==='string'&&data[0].context[k]===data[1].context[k];});if(!matched){sec._comparisonRows=[];status.textContent='Cannot compare: recorded clock, timing or byte boundaries differ or are missing. No ratio is inferred.';return;}var rows=M.compare(data[0],data[1]);sec._comparisonRows=rows;status.textContent=rows.length?'Measured comparison · '+rows.length+' matching cases; inspect controls before attribution.':'No matching cases. Keep work and timing boundaries identical.';
      U.table(out,['Context','Run A','Run B'],['cpu_model','architecture','kernel','cpu','smt_siblings','clock','timing_boundary','source_sha256','compiler','compile_command','page_size','actual_mapping_page_size','thp','governor','boost','notes','quick'].map(function(k){return [k,...data.map(function(d){return d.context[k]===undefined?'not recorded':typeof d.context[k]==='object'?JSON.stringify(d.context[k]):String(d.context[k]);})];}));
      U.table(out,['Mode / bytes / chains / steps / operations / seed','Trials A / B','Median A ns/op','Median B ns/op','B / A time ratio'],rows.map(function(q){return [q.key,q.trialsA+' / '+q.trialsB,q.a.toFixed(3),q.b.toFixed(3),q.ratio.toFixed(3)];}));
      var same=data[0].context.source_sha256&&data[0].context.source_sha256===data[1].context.source_sha256;U.text('p',out,same?'Source hashes match. Compiler output, frequency, page state, topology and memory configuration still require comparison.':'Source hashes differ or are missing. Treat this as a descriptive comparison of different/unknown programs, not an architecture-controlled result.');U.text('p',out,'Completion flags: A '+(data[0].complete===true?'complete':'partial/unknown')+', B '+(data[1].complete===true?'complete':'partial/unknown')+'. Quick harness runs are validation only. Report dispersion and raw samples, not just the ratio. Working-set plateaus and supported PMU evidence help explain a difference; clocks, DIMMs and placement can dominate it.');
    }
    U.text('a',sec,'Native measurement controls and run protocol',{href:'benchmarks/README.md'});
  }
  App.extendChapter('map',reference);App.extendChapter('stores',ordering);App.extendChapter('hier',inclusion);App.extendChapter('xlate',granules);App.extendChapter('perf',compare);
  ['map','code','core','xlate','l1d','hier','dram','stores','coh','pref','dev','e2e'].forEach(function(id){App.extendChapter(id,function(root){var lead=root.querySelector('.learning-scene .scene-lead');if(!lead)return;var box=h('details',{'class':'evidence-scope'},lead);U.text('summary',box,'Evidence and implementation scope');U.text('p',box,'Teaching-model parameters describe the chosen capacities, clocks and policies. The instruction and page-table walkthrough is explicitly x86-64; DRAM examples are scoped DDR4. Implementation facts and measured observations retain named generations, sources and boundaries.');U.text('a',box,'Inspect the evidence contract and implementation cases',{href:'#map/reference'});});});
})();
